name: 'Custom Footer Block'
description: 'Places the custom footer menu block.'

recipes:
  - seed_cms_custom_footer_menu

install:
  - block

config:
  strict: false
  import:
    block:
      - block.block.drupal_cms_olivero_menublog.yml
