# uuid: e79ab747-c9ac-453d-b1a6-4494d5fed2b0
langcode: en
status: true
dependencies:
  config:
    - field.storage.taxonomy_term.field_perfil_corto
    - taxonomy.vocabulary.authors
id: taxonomy_term.authors.field_perfil_corto
field_name: field_perfil_corto
entity_type: taxonomy_term
bundle: authors
label: 'perfil corto'
description: ''
required: true
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
