# uuid: 3063c510-81a4-4acf-87d2-81a5d7ff559a
langcode: en
status: true
dependencies:
  module:
    - node
    - paragraphs
id: paragraph.field_entradas_destacadas
field_name: field_entradas_destacadas
entity_type: paragraph
type: entity_reference
settings:
  target_type: node
module: core
locked: false
cardinality: 3
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
