# uuid: 70ff756a-4801-4c3c-9fea-82351d1151f2
langcode: en
status: true
dependencies:
  module:
    - node
    - paragraphs
id: paragraph.field_te_pude_interesar
field_name: field_te_pude_interesar
entity_type: paragraph
type: entity_reference
settings:
  target_type: node
module: core
locked: false
cardinality: -1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
