# uuid: f2cebd4c-4a06-4d83-bc8a-92536557c7de
langcode: en
status: true
dependencies:
  config:
    - field.storage.paragraph.field_body
    - filter.format.content_format
    - paragraphs.paragraphs_type.texto
  module:
    - text
id: paragraph.texto.field_body
field_name: field_body
entity_type: paragraph
bundle: texto
label: body
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  allowed_formats:
    - content_format
field_type: text_long
