# uuid: c75d6c55-4b75-43d0-aae5-5fc4ceba3153
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_author
    - node.type.blog
    - taxonomy.vocabulary.authors
id: node.blog.field_author
field_name: field_author
entity_type: node
bundle: blog
label: Author
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      authors: authors
    sort:
      field: name
      direction: asc
    auto_create: false
    auto_create_bundle: ''
field_type: entity_reference
