# uuid: 62eb4d19-a34f-4c92-b24f-79e6f44cb5c6
langcode: en
status: true
dependencies:
  module:
    - scheduler
third_party_settings:
  scheduler:
    expand_fieldset: when_required
    fields_display_mode: vertical_tab
    publish_enable: false
    publish_past_date: error
    publish_past_date_created: false
    publish_required: false
    publish_revision: false
    publish_touch: false
    show_message_after_update: true
    unpublish_enable: false
    unpublish_required: false
    unpublish_revision: false
name: authors
vid: authors
description: 'autores de la publicacion'
weight: 0
new_revision: false
