name: 'Custom Footer Menu'
description: 'Creates a separate footer menu and places it as a block.'

install:
  - menu_ui
  - menu_link_content

config:
  strict: false
  import:
    menu_ui:
      - system.menu.footer_custom
    menu_link_content:
      - menu_link_content.menu_link_content.terms_of_use
